# Generated by Django 3.2.7 on 2021-10-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.perfil'),
        ),
    ]
