# Generated by Django 3.2.7 on 2021-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vuelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='este',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='norte',
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='este',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='norte',
            field=models.FloatField(default=0),
        ),
    ]
