# Generated by Django 3.2.7 on 2021-10-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vuelos', '0002_auto_20211004_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovuelo',
            name='NumeroSillasVendidas',
            field=models.IntegerField(default=0),
        ),
    ]
